### ISSUE TITLE
Proposal: Numeric literals in object keys

### ISSUE THREAD

**Issue by AldoMX** [json5/json5-spec#31] opened 2020-10-03 15:03 UTC
With the current spec, the following JSON is invalid because the keys are not a valid identifier name:

```javascript
{
  employeesById: {
    1: { name: "Huey", age: 30 },
    2: { name: "Dewey", age: 29 },
    3: { name: "Louie", age: 31 }
  }
}
```

This ticket is to propose allowing numeric literals alongside identifier names for object keys.

**Comment by jordanbtucker** [comment] 2020-10-03 15:11
Thank you for this proposal. It is a duplicate of #10. Please see the comments there.

**Closed as completed by jordanbtucker** 2020-10-03 15:11 UTC
